apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: pipecd-example-simple-bpolicy
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"workload":"distributed"}